### ISSUE TITLE
Client fails to start

### ISSUE THREAD

**Issue by boucher** [aeirola/slack-irc-client#2]
```
info: Starting slack-irc-client
info: Connecting to Slack...
/usr/local/lib/node_modules/slack-irc-client/node_modules/slack-client/lib/clients/rtm/client.js:183
    this.logger('verbose', 'attempting to connect via the RTM API');
         ^

TypeError: this.logger is not a function
    at RTMClient.start (/usr/local/lib/node_modules/slack-irc-client/node_modules/slack-client/lib/clients/rtm/client.js:183:10)
    at Object.initSlackListener [as init] (/usr/local/lib/node_modules/slack-irc-client/lib/slack-listener.js:35:15)
    at start (/usr/local/lib/node_modules/slack-irc-client/bin/server.js:80:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/slack-irc-client/bin/server.js:84:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
```

Running on OS X, node v5.1.1.

**Comment by aeirola** [comment]
This has now been fixed in version `0.1.5`
