### ISSUE TITLE
May abruptly crash for no reason

### ISSUE THREAD

**Issue by aeirola** [aeirola/slack-irc-client#9]
Console output:

```
verbose: attempting to connect via the RTM API  
verbose: rtm.start successful, attempting to open websocket URL  
info: Slack: Connected to Slack  
info: IRC listener already initialized, skipping.  
info: message received on reconnect with no registered callback:  
[object Object]  
verbose: attempting to connect via the RTM API  
verbose: rtm.start successful, attempting to open websocket URL  
info: Slack: Connected to Slack  
info: IRC listener already initialized, skipping.  
info: message received on reconnect with no registered callback:  
[object Object]  
/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/lib/clients/rtm/client.js:761  
      responseHandler.fulfill(res);  
                     ^  
  
TypeError: Cannot read property 'fulfill' of undefined  
    at RTMClient._handleMsgResponse (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/lib/clients/rtm/client.js:761:22)  
    at RTMClient._handlePong (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/lib/clients/rtm/client.js:595:8)  
    at RTMClient._handleWsMessageInternal (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/lib/clients/rtm/client.js:415:10)  
    at RTMClient.handleWsMessage (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/lib/clients/rtm/client.js:399:10)  
    at WebSocket.wrapper (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/lodash/index.js:3095:19)  
    at emitTwo (events.js:87:13)  
    at WebSocket.emit (events.js:172:7)  
    at Receiver.ontext (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/WebSocket.js:816:10)  
    at /home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:477:18  
    at Receiver.applyExtensions (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:364:5)  
    at /home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:466:14  
    at Receiver.flush (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:340:3)  
    at Receiver.opcodes.1.finish (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:482:12)  
    at Receiver.expectHandler (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:457:31)  
    at Receiver.add (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/Receiver.js:95:24)  
    at TLSSocket.realHandler (/home/users/aeirola/local/lib/node_modules/slack-irc-client/node_modules/@slack/client/node_modules/ws/lib/WebSocket.js:800:20)  
    at emitOne (events.js:77:13)  
    at TLSSocket.emit (events.js:169:7)  
    at readableAddChunk (_stream_readable.js:146:16)  
    at TLSSocket.Readable.push (_stream_readable.js:110:10)  
    at TLSWrap.onread (net.js:523:20)  
```

**Comment by tiagopedras** [comment]
Having similar problems like this. Getting the same warning when RTM client connects:
- info: message received on reconnect with no registered callback:

**Comment by aeirola** [comment]
This seems to be a problem in `node-slack`: https://github.com/slackhq/node-slack-sdk/issues/226

I'll update the dependecy version, which should fix the problem
